### ISSUE TITLE
Entering my api key

### ISSUE THREAD

**Issue by paddywills** [ms32035/home-assistant-ubibot#4]
I see the yaml section is:
`platform: ubibot
api_key: !secret ubibot_apikey
channel: !secret ubibot_channel_number
scan_interval: 900`

so if my channel is 12345 do I amend to
`channel: !secret 12345`
or 
`channel: 12345`
or
`channel: 12345 ubibot_channel_number`

**Comment by ms32035** [comment]
That is documented in HA secrets documentation
https://www.home-assistant.io/docs/configuration/secrets/

**Comment by paddywills** [comment]
I have installed your repo via HACS
I have then added the bit of YAML code as per your instructions

<img width="412" alt="Screenshot 2023-10-02 at 18 08 41" src="https://github.com/ms32035/home-assistant-ubibot/assets/26979785/49b1124f-f6b4-48e8-93cf-194cc8f5defc">


I have put the 2 variable into the secrets file

I get the error
Integration error: scan_interval - Integration 'scan_interval' not found. 
Integration error: platform - Integration 'platform' not found. 
Integration error: api_key - Integration 'api_key' not found. 
Integration error: channel - Integration 'channel' not found.

**Comment by qrockz** [comment]
@ms32035 
I get also the same errors as @paddywills

I think it has something to do with the account key from ubibot. But how can I get it to work?

**Comment by ms32035** [comment]
@qrockz this is well documented in the standard documentation for HA YAML configuration:
https://www.home-assistant.io/docs/configuration/yaml/#example-of-nested-mapping

This integration **provides sensors**, so you should **configure a sensor** not add a set of top level yaml elements which violate the configuration schema.

**Comment by qrockz** [comment]
@ms32035 

I get no values. 
![sensor](https://github.com/ms32035/home-assistant-ubibot/assets/56853194/edc4a92e-2ef5-46fd-a849-9051608b0dc9)

configuration.yaml
```
sensor:   
 - platform: ubibot
   api_key: !secret ubibot_apikey
   channel: !secret ubibot_channel_number
   scan_interval: 900
```
_ubibot_apikey_ and _ubibot_channel_number_ are both defined in _secrets.yaml_

EDIT:

It works now BUT:
the term _api_key_ in the configuration _readme_ is misleading. I had to use the _account key_ from ubibot (account/security settings/account key)
![accountkey](https://github.com/ms32035/home-assistant-ubibot/assets/56853194/4b0a65f0-0448-4dd1-91eb-99b1a90f91e8) instead of the api keys
![apikey](https://github.com/ms32035/home-assistant-ubibot/assets/56853194/754de429-2f90-4ff8-988d-3183d1fabf69)

in the usage example you use the term _api_key_ but in your code you use the _account_key_.

Ubibot provides account key and api keys. I recommend to replace _api_key_ with with _account_key_ in the readme configuration.
